// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaaBGsAWU5j8pjT1BD4dtn5_iAEQ1jxmc',
    appId: '1:204871241196:web:d1faecac830742d006c4c9',
    messagingSenderId: '204871241196',
    projectId: 'fir-auth-app-c8ec4',
    authDomain: 'fir-auth-app-c8ec4.firebaseapp.com',
    storageBucket: 'fir-auth-app-c8ec4.firebasestorage.app',
    measurementId: 'G-CKR2VPJ51L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLxwszReF-u0s0N2ZVeA1J1omJJmSXOog',
    appId: '1:204871241196:android:149231c09cc8be9106c4c9',
    messagingSenderId: '204871241196',
    projectId: 'fir-auth-app-c8ec4',
    storageBucket: 'fir-auth-app-c8ec4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrwRMkOwNfdntS8vNDsF1k8I5NcCI3afs',
    appId: '1:204871241196:ios:d05a1dcf02aa2dad06c4c9',
    messagingSenderId: '204871241196',
    projectId: 'fir-auth-app-c8ec4',
    storageBucket: 'fir-auth-app-c8ec4.firebasestorage.app',
    iosBundleId: 'com.example.loginNiChardet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrwRMkOwNfdntS8vNDsF1k8I5NcCI3afs',
    appId: '1:204871241196:ios:d05a1dcf02aa2dad06c4c9',
    messagingSenderId: '204871241196',
    projectId: 'fir-auth-app-c8ec4',
    storageBucket: 'fir-auth-app-c8ec4.firebasestorage.app',
    iosBundleId: 'com.example.loginNiChardet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaaBGsAWU5j8pjT1BD4dtn5_iAEQ1jxmc',
    appId: '1:204871241196:web:47808b6f6be9696c06c4c9',
    messagingSenderId: '204871241196',
    projectId: 'fir-auth-app-c8ec4',
    authDomain: 'fir-auth-app-c8ec4.firebaseapp.com',
    storageBucket: 'fir-auth-app-c8ec4.firebasestorage.app',
    measurementId: 'G-SXB3YNE8D9',
  );

}